version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: api
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 33067:3306  
    volumes:
      - .db:/var/lib/mysql
volumes:
  db:          