version: '3.4'

services:
  cardoperationmysql:
    image: cardoperationmysql
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 9090:9090
      - 5005:5005
